version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "Pidel123123_"
      REDIS_DB: "0"
      REDIS_PORT: "6379"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
